### ISSUE TITLE
crashing when cubanedicarboxylic acid reacts in vat

### ISSUE THREAD

**Issue by gri16m** [petrolpark/Destroy#375] opened 2024-06-14 01:49 UTC
In a vat, whenever cubanedicarboxylic acid has a test tube of anything that'll react with it my game freezes and crashes. This happens every time

Steps to reproduce:

1. Construct a vat
2. Add test tube of cubanedicarboxylic acid
3. Add test tube of phosgene. Alternatively add magic reductant  (both ways will crash the game)

 - Destroy 0.8
 - Create 0.5.1f
 - JEI 15.3.0.4

[crash-2024-06-13_20.48.03-server.txt](https://github.com/user-attachments/files/15830533/crash-2024-06-13_20.48.03-server.txt)

gri16m

**Comment by petrolpark** [comment] 2024-06-14 13:22
This will be a duplicate of #294 (and numerous others). It is fixed in the development build. That will be coming out in a more reasonable time frame now that my exams are finished. I know it's annoying but hang in there.

**Closed as completed by petrolpark** 2024-06-14 13:22 UTC
Labels: 🐛 Bug

**Comment by gri16m** [comment] 2024-06-16 20:46
It's no worries, I'm appreciative you put your time into making this mod.
