### ISSUE TITLE
Druken slipping acceleration

### ISSUE THREAD

**Issue by MineKingTop** [petrolpark/Destroy#53] opened 2024-01-06 10:32 UTC
Similar to #48 druken slipping causes infinite acceleration or stuff, physics I guess.
The strip is 235 blocks long. 

https://github.com/petrolpark/Destroy/assets/97742326/ebdd81f9-ef7b-4fbc-8c62-8ab5e9e6aa35

**Comment by petrolpark** [comment] 2024-01-06 13:12
Duplicate of #21, which has been fixed in 0.3. Thank you for you help anyway :)

**Closed as not planned by petrolpark** 2024-01-06 13:12 UTC
Labels: 🐛 Bug
