### ISSUE TITLE
Crash when standing on a depot

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#14] opened 2024-01-05 14:01 UTC
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

To recreate: place down a depot and jump onto it, the second you touch it from the top, the game freezes without immediately crashing, but never unfreezes.

[crash-2024-01-05_08.59.41-server.txt](https://github.com/petrolpark/Destroy/files/13842901/crash-2024-01-05_08.59.41-server.txt)

**Comment by Nexusuxen** [comment] 2024-01-07 18:33
Looks like this has been mentioned in other bugs reports, but I'd like to compile my experiences here in this open one. Apparently the issue is fixed in 0.3, but that is not yet released and I'd like to submit more data as that has the slight chance of being useful!

Depots are intensely bugged at the moment, and Destroy is directly referenced in the crash logs involving them. The crashes are Ticking Entity crashes for interactions, and Exception in server tick loop crashes for the issue above. The following interactions cause a crash:
- Right-clicking the depot with any item, including to place a mechanical press (Ticking entity crash, no crash loop)
- Throwing an item onto the depot (Ticking entity crash, crash loop (fixable with Neruina)
- Standing on the depot (Exception in server tick loop, crash loop (unfixable?))

Unfortunately I've yet to resolve this last bullet point, and until 0.3 is released, my world is bricked. A shame, but expected with an alpha version of a mod!
Here are the various crash logs involved in the above issue that I have. Chronologically, the earliest log(s) will be for the first bullet above, and the latest log(s) will be for the final bullet above, with the middle bullet corresponding to some of the middling crash logs.
[crash-2024-01-07_13.25.37-server.txt](https://github.com/petrolpark/Destroy/files/13854526/crash-2024-01-07_13.25.37-server.txt)
[crash-2024-01-07_13.25.24-server.txt](https://github.com/petrolpark/Destroy/files/13854527/crash-2024-01-07_13.25.24-server.txt)
[crash-2024-01-07_13.25.10-client.txt](https://github.com/petrolpark/Destroy/files/13854528/crash-2024-01-07_13.25.10-client.txt)
[crash-2024-01-07_13.25.11-server.txt](https://github.com/petrolpark/Destroy/files/13854529/crash-2024-01-07_13.25.11-server.txt)
[crash-2024-01-07_13.22.48-client.txt](https://github.com/petrolpark/Destroy/files/13854530/crash-2024-01-07_13.22.48-client.txt)
[crash-2024-01-07_13.18.00-server.txt](https://github.com/petrolpark/Destroy/files/13854531/crash-2024-01-07_13.18.00-server.txt)
[crash-2024-01-07_13.18.00-client.txt](https://github.com/petrolpark/Destroy/files/13854532/crash-2024-01-07_13.18.00-client.txt)
[crash-2024-01-07_13.17.08-client.txt](https://github.com/petrolpark/Destroy/files/13854533/crash-2024-01-07_13.17.08-client.txt)
[crash-2024-01-07_13.17.08-server.txt](https://github.com/petrolpark/Destroy/files/13854534/crash-2024-01-07_13.17.08-server.txt)
[crash-2024-01-07_13.16.39-client.txt](https://github.com/petrolpark/Destroy/files/13854535/crash-2024-01-07_13.16.39-client.txt)
[crash-2024-01-07_13.16.39-server.txt](https://github.com/petrolpark/Destroy/files/13854536/crash-2024-01-07_13.16.39-server.txt)
[crash-2024-01-07_13.15.31-client.txt](https://github.com/petrolpark/Destroy/files/13854537/crash-2024-01-07_13.15.31-client.txt)
[crash-2024-01-07_13.15.05-client.txt](https://github.com/petrolpark/Destroy/files/13854538/crash-2024-01-07_13.15.05-client.txt)
[crash-2024-01-07_13.14.42-client.txt](https://github.com/petrolpark/Destroy/files/13854539/crash-2024-01-07_13.14.42-client.txt)
[crash-2024-01-07_13.27.06-server.txt](https://github.com/petrolpark/Destroy/files/13854540/crash-2024-01-07_13.27.06-server.txt)

**Comment by petrolpark** [comment] 2024-01-08 23:32
All due to the same thing. That is now fully dealt with. Previously bricked worlds should now be openable.

**Closed as completed by petrolpark** 2024-01-08 23:32 UTC
Labels: 🐛 Bug
