### ISSUE TITLE
[Suggestion] Compatibility with Create: Diesel Generators

### ISSUE THREAD

**Issue by MineKingTop** [petrolpark/Destroy#44] opened 2024-01-06 00:39 UTC
Create: Diesel generators also has crude oil, so it makes sense that you coud use both crude oils when distilling.
At the moment it is not possible.

**Comment by petrolpark** [comment] 2024-01-07 11:51
I'm going to count this as a duplicate of #56. I'll close this thread, but it's still on the table.

**Closed as not planned by petrolpark** 2024-01-07 11:51 UTC
Labels: 💭 Suggestion
