### ISSUE TITLE
I... I don't understand how to use this mod.

### ISSUE THREAD

**Issue by AngelOfCreation** [petrolpark/Destroy#176] opened 2024-01-21 15:40 UTC
I'm so confused. I built a vat but what do I with it? I want to try the 'Ostwald process' but it wants a bunch of chemicals and I don't know how to get them. And even if I did have them, I don't know what to do with them. Do I just pump them all into the vat with fluid pipes? The Ponder Index is not helpful at all.

The chemicals all list stuff like mass, boiling point, and liquid density. Is this all relevant or is it just there for fun? Do I need to do math to use this mod?

This mod feels too complicated, it's very off putting.

**Comment by Andromeda-Galaxy29** [comment] 2024-01-21 17:09
There really should be some guide or wiki on how to use this mod. Without much chemistry knowledge it's practically impossible to use it

**Comment by TheRedCrafter344** [comment] 2024-01-21 18:13
Yea there is no guide yet. But I think a guide/wiki would have to wait for the mod to be half-usable before it could start being written (and at the moment, it isn't really)

**Comment by petrolpark** [comment] 2024-01-21 22:43
This isn't really a bug report, but I'm going to assume this is a duplicate of #60.

**Closed as not planned by petrolpark** 2024-01-21 22:43 UTC
Labels: 💭 Suggestion
