### ISSUE TITLE
Dedicated Server Crash/Hang

### ISSUE THREAD

**Issue by windth001** [petrolpark/Destroy#147] opened 2024-01-17 02:21 UTC
The server launches with no issue until I add Destroy 0.3 to the server and launch. Kinda of just hangs there and even when stopping the server it takes a bit and crashes with return value: 143. Same mods launching a singleplayer world has no issues tho. Forge 47.2.19

[crashlog.log](https://github.com/petrolpark/Destroy/files/13957852/crashlog.log)

**Comment by petrolpark** [comment] 2024-01-17 12:30
Duplicate of #102 fixed in 0.4.

**Closed as completed by petrolpark** 2024-01-17 12:30 UTC
Labels: 🐛 Bug
