### ISSUE TITLE
Test tube crashes game when used on blocks

### ISSUE THREAD

**Issue by DanielSDT** [petrolpark/Destroy#300] opened 2024-02-18 20:03 UTC
When an empty test tube is "used" on a block, the game crashes. I haven't tested all blocks, but in general if it doesn't have an inventory or isn't from create, it causes a crash. 
Here is one of the the crash reports
[crash-2024-02-18_19.50.37-client.txt](https://github.com/petrolpark/Destroy/files/14324184/crash-2024-02-18_19.50.37-client.txt)

**Comment by petrolpark** [comment] 2024-02-19 08:45
Duplicate of #265.

**Closed as not planned by petrolpark** 2024-02-19 08:45 UTC
Labels: 🐛 Bug
