### ISSUE TITLE
Multiple crashes

### ISSUE THREAD

**Issue by ghost** [petrolpark/Destroy#4] opened 2024-01-05 11:20 UTC
Crash when giving a bucket and spade to a baby villager.
Crash while pondering over the bubble cap and differential.
Crash when placing a coaxial cogwheel, a centrifuge, and a dynamo.
Crash when searching for the recipe for atoms in JEI.

**Comment by petrolpark** [comment] 2024-01-05 11:44
- 2 - Fixed in 0.2. 
- 3 - Fixed in 0.2.
- 1 & 4 - I'm unable to reproduce these. Could you send the crash reports and any other information (what mods and versions you are running). For 4, which molecule where you trying to search the recipe for?

**Comment by MindFaer** [comment] 2024-01-05 12:34
To add onto the first crash, right clicking with a bucket and spade also causes a crash

[crash-2024-01-05_07.33.32-client.txt](https://github.com/petrolpark/Destroy/files/13842073/crash-2024-01-05_07.33.32-client.txt)

**Comment by petrolpark** [comment] 2024-01-05 12:57
That one should be fixed in 0.2. If possible, could @Pnaabnloo provide more information on the crash when searching for recipes in JEI. Do you have EMI installed?

**Comment by ghost** [comment] 2024-01-05 13:09
I dont have EMI. It happends with 
cyclohexene:
[crash-2024-01-05_14.03.25-client.txt](https://github.com/petrolpark/Destroy/files/13842400/crash-2024-01-05_14.03.25-client.txt)
chlorine:
[crash-2024-01-05_14.04.35-client.txt](https://github.com/petrolpark/Destroy/files/13842415/crash-2024-01-05_14.04.35-client.txt)
Glycerol:
[crash-2024-01-05_14.07.21-client.txt](https://github.com/petrolpark/Destroy/files/13842417/crash-2024-01-05_14.07.21-client.txt)
And many more

**Comment by ghost** [comment] 2024-01-05 13:21
I also found a crash on the 3rd stage of Vat's ponder: 
[crash-2024-01-05_14.20.42-client.txt](https://github.com/petrolpark/Destroy/files/13842541/crash-2024-01-05_14.20.42-client.txt)

**Comment by petrolpark** [comment] 2024-01-05 14:32
All fixed in 0.2.

**Closed as completed by petrolpark** 2024-01-05 14:32 UTC
Labels: 🐛 Bug
