### ISSUE TITLE
Crash with rotational speed controller

### ISSUE THREAD

**Issue by MagmaCube90** [petrolpark/Destroy#68] opened 2024-01-07 01:16 UTC
when a differential is placed above a rotational speed controller and the differential is powered and then the rotational speed controller is powered the game crashes

**Comment by petrolpark** [comment] 2024-01-07 14:57
Fixed in 0.3. The Differential will now just break, which is the intended behaviour.

**Closed as completed by petrolpark** 2024-01-07 14:57 UTC
Labels: 🐛 Bug
