### ISSUE TITLE
Game crashes when a Vat explodes with "Immersive Aircraft" installed

### ISSUE THREAD

**Issue by Theodorteo** [petrolpark/Destroy#400] opened 2024-07-20 16:04 UTC
Filling a vat with too much of a solution will make it explode. If Immersive Aircraft is installed, the game crashes instead. When relaunching the game and reopening the world, no sign of explosion is present and the vat controller doesn't recognise the vat structure until you right-click it.

**Installed Mods**
Create 0.5.1f
Destroy 0.8
Immersive Aircraft 1.0.1

**Crash Message**
The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_9236_()" because "source" is null
Exit Code: -1

**[Crash Report](https://github.com/user-attachments/files/16321586/crash.repot.txt)**

**[debug.log](https://github.com/user-attachments/files/16321595/debug.log)**

Build I used to produce this bug:
![image](https://github.com/user-attachments/assets/589b6b1d-c318-48b2-a3cf-63ea1efb09e6)

MC Username: Theodorteo

**Comment by Lukas0094** [comment] 2024-07-21 12:40
Apparently this occurs because the “ia$vehicleTrace” method in Immersive Aircraft's “ProjectileUtilMixin” class is executed when the vat controller explodes. I haven't looked into why this happens, but within this method there is a parameter “source”. The method tries to call the “level” method of “source”. The problem is that whenever destroy calls the method by mistake, the parameter “source” is null. This triggers a NullPointerExeption and the game crashes. A temporary solution would be to check if “source” is null and if so, exit the method.
**I take no responsibility if this solution does not work in some cases or if this solution causes other problems!**
I'm not able to upload the .jar file, but I suggest you also contact the owner of Immersive Aircraft.
![fix](https://github.com/user-attachments/assets/b89eb4c6-1b4e-46df-9da1-28434bda330e)

**Comment by petrolpark** [comment] 2024-09-15 13:28
Fixed on Immersive Aircraft's end.

**Closed as completed by petrolpark** 2024-09-15 13:28 UTC
Labels: 🐛 Bug, 🤝 Compatibility
