### ISSUE TITLE
Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by Mikeatron-User** [petrolpark/Destroy#177] opened 2024-01-21 15:59 UTC
Minecraft `1.20.1`
Forge Version `47.2.20`
Mod Version `0.5`

Crash Log: <https://mclo.gs/T9x8v1e>

**Comment by petrolpark** [comment] 2024-01-21 22:47
Duplicate of #167.

**Closed as completed by petrolpark** 2024-01-21 22:47 UTC
Labels: 🐛 Bug
