### ISSUE TITLE
Bug: Brine + Mercury electrolysis not working

### ISSUE THREAD

**Issue by skymory-24** [petrolpark/Destroy#164] opened 2024-01-20 15:58 UTC
Electrolysing brine and mercury to produce sodium almalgam and chlorine solution does not work in versions 0.4 and 0.5

Test setup (tested on versions 0.3 (functions perfectly), 0.4 and 0.5 (both non-functional)):

![image](https://github.com/petrolpark/Destroy/assets/49978560/f413a803-3395-41c5-bf54-db161742f841)

pulse extension setup used to supply electrolysis basin with 250mB of both fluids in steps of 50mB (button pressed 5 times per reaction)

**Comment by petrolpark** [comment] 2024-01-20 17:27
Duplicate of #163.

**Closed as not planned by petrolpark** 2024-01-20 17:27 UTC
Labels: 🐛 Bug
