### ISSUE TITLE
Another person is unable to join my lan server

### ISSUE THREAD

**Issue by ErrorNotF0und** [petrolpark/Destroy#64] opened 2024-01-06 19:33 UTC
![изображение_2024-01-06_203323807](https://github.com/petrolpark/Destroy/assets/155847246/41e7cc94-1afa-4e48-a679-00746339639b)

**Comment by petrolpark** [comment] 2024-01-07 11:32
Does this error appear when you open the world up to LAN, or is this is the error they get when trying to join?

**Comment by ErrorNotF0und** [comment] 2024-01-07 12:20
When they are trying to join.

**Comment by petrolpark** [comment] 2024-01-07 18:41
Could you attach their log file? (You will need to reproduce this error). Thanks

**Comment by ErrorNotF0und** [comment] 2024-01-07 21:05
[latest.log](https://github.com/petrolpark/Destroy/files/13854939/latest.log)
Only happens when using Destoy mod, in the log its just disconnected.

**Comment by Xuezhi-Yang** [comment] 2024-01-09 02:15
The bug exists in version 0.3

**Comment by BowBoy1** [comment] 2024-01-13 09:06
You've probably already figured this out but it seems to be an issue relating to the ICU library

**Comment by petrolpark** [comment] 2024-01-13 15:02
The reference to the ICU `DateFormat` definitely caused #102, and has been fixed in 0.4, by replacement of the class with the built-in `java.util.DateFormat`. @BowBoy1 I've not investigated this one extensively, why do you think that? It doesn't seem that that caused the crash in the log above. Hopefully you're right though, as that would mean it's already fixed.

**Comment by BowBoy1** [comment] 2024-01-13 17:24
My bad, I found this open issue through #106 and thought it was related to the issue I was having earlier. This one's still a pretty major concern though, it still breaks multiplayer. If I find any useful information on this problem I'll be sure to share it.

**Comment by petrolpark** [comment] 2024-01-18 19:47
Fixed in 0.4. Or at least I can't replicate anymore...

**Closed as completed by petrolpark** 2024-01-18 19:47 UTC
Labels: 🐛 Bug

**Comment by Xuezhi-Yang** [comment] 2024-01-19 03:56
Great, I can add it to the server of my friends and me.
