### ISSUE TITLE
I'm not sure that DEEPSLATE_NICKEL_ORE should have fluorite tag.

### ISSUE THREAD

**Issue by semenishchev** [petrolpark/Destroy#279] opened 2024-02-14 12:14 UTC
<img width="958" alt="Снимок экрана 2024-02-14 в 13 13 40" src="https://github.com/petrolpark/Destroy/assets/38401696/8b3c206c-d0ce-426c-991b-cef9a89262f5">

**Comment by petrolpark** [comment] 2024-02-14 14:29
Duplicate of #264, fixed.

**Closed as completed by petrolpark** 2024-02-14 14:29 UTC
Labels: 🐛 Bug
