### ISSUE TITLE
Test Tube Crash when used on any block

### ISSUE THREAD

**Issue by YukarinnAM** [petrolpark/Destroy#338] opened 2024-03-16 14:54 UTC
Bug similar to a [previous one](https://github.com/petrolpark/Destroy/issues/265) but it was mentioned to happen on fluids

**Describe the bug**

The game clashes the moment one uses a test tube on any block
i at first noticed this bug when messing around in a creative world and miss clicking a basin with the smooth stone floor i had, it then crashed, this happened many more times so then i tested it on grass block and it too crashed, finally i exited the modpack i was using then went to a fresh one with only Create and Destroy to see if it was a problem with another mod i had
There i made a new world, took a test tube from creative, and left clicked on stone, it then crashed as well

**To Reproduce**

Simply use a test tube on any block of the world, happened to me on: Glass Block, Smooth Stone and Stone
i did not test on other but this alone could probably indicate to happen on others

**Expected Behavior**

Nothing

**System Information**

Tested on a pack with the following mod:
Create: create-1.20.1-0.5.1.f
Destroy: destroy-1.20.1-0.8

**Additional context**

Crash-report
[crash-2024-03-16_11.40.39-client.txt](https://github.com/petrolpark/Destroy/files/14623965/crash-2024-03-16_11.40.39-client.txt)

**Comment by petrolpark** [comment] 2024-03-17 21:48
Same root cause as #265, which is fixed in 1.0.

**Closed as completed by petrolpark** 2024-03-17 21:48 UTC
Labels: 🐛 Bug
