### ISSUE TITLE
[BUG] Cant join a friend's world using Essential

### ISSUE THREAD

**Issue by Stonkman** [petrolpark/Destroy#58] opened 2024-01-06 16:42 UTC
When i try joining my friends world shared Using Essential mod, i get an error message.
He can create and play the world just fine, but no one can join.

How to recreate:
-load minecraft with Destroy and Essential
-Invite someone to the world
-the invited person would get the error message
![image](https://github.com/petrolpark/Destroy/assets/69413962/7eb23e66-63dc-4414-a511-17cb0cf3365b)

Link to Essential:
https://modrinth.com/mod/essential
(or just install it from curseforge app)

**Comment by petrolpark** [comment] 2024-01-06 16:49
Could you attach the section of the server log when they try to join? I'm not sure how different essentials hosted worlds are to vanilla servers, but vanilla servers are currently slightly broken but fixed in 0.3.

**Comment by Stonkman** [comment] 2024-01-06 17:47
![image](https://github.com/petrolpark/Destroy/assets/69413962/35e0a6f7-ea30-4a3e-901c-5d911ee8ce04)

this is the only screen he gave me

**Comment by SubhanAfz** [comment] 2024-01-06 18:27
Hello, I have the same error when I try to join, here is my log file
[latest.log](https://github.com/petrolpark/Destroy/files/13850812/latest.log)

**Comment by petrolpark** [comment] 2024-01-07 11:36
> ![image](https://private-user-images.githubusercontent.com/69413962/294706840-35e0a6f7-ea30-4a3e-901c-5d911ee8ce04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2Mjc0NjgsIm5iZiI6MTcwNDYyNzE2OCwicGF0aCI6Ii82OTQxMzk2Mi8yOTQ3MDY4NDAtMzVlMGE2ZjctZWEzMC00YTNlLTkwMWMtNWQ5MTFlZThjZTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDExMzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MmM1MTUwMzM4MDdjOGNiMDE1MjliNjdiZWE2MTU0YjkyNDQ1NDcyYThhYmVjNzJlYzAxNjFiMzdmN2VlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0QZBytFrJ7QhkDuvxyliMqEN9rlSMLTW1eNGYd6gE-w)
> 
> this is the only screen he gave me

This doesn't appear to be due to Destroy. If you remove everything except, Create, Destroy and Essential do you still get the crash?

**Comment by REDDENoWang** [comment] 2024-01-14 15:48
Hello, the same error occurred when I tried to connect to the LAN with my roommate. I found that I deleted this mod and there was no such error after that

The error occurs in the joiner, the game does not crash

here is the logs:

[joiner-debug.log](https://github.com/petrolpark/Destroy/files/13932072/joiner-debug.log)
[host 2024-01-14-17.log](https://github.com/petrolpark/Destroy/files/13932083/host.2024-01-14-17.log)

**Comment by petrolpark** [comment] 2024-01-18 13:06
> Hello, the same error occurred when I tried to connect to the LAN with my roommate. I found that I deleted this mod and there was no such error after that
> 
> The error occurs in the joiner, the game does not crash
> 
> here is the logs:
> 
> [joiner-debug.log](https://github.com/petrolpark/Destroy/files/13932072/joiner-debug.log) [host 2024-01-14-17.log](https://github.com/petrolpark/Destroy/files/13932083/host.2024-01-14-17.log)

Remove every other mod; these logs are impossible to read.

**Comment by petrolpark** [comment] 2024-01-18 19:50
The cause seems to be the same as #64, which has been fixed in 0.4. If you still can't join with Essential, resubmit a report. It probably won't be the highest priority though.

**Closed as completed by petrolpark** 2024-01-18 19:50 UTC
Labels: 🐛 Bug, 🤝 Compatibility
