### ISSUE TITLE
destroy dont work in mp.

### ISSUE THREAD

**Issue by nicbou0321** [petrolpark/Destroy#116] opened 2024-01-11 03:49 UTC
while trying to play mc in 1.20.1, it took me hours before i realized destroy was causing the issue. 
local server, my friend has this message when trying to join, it insta disconnects. 
![image](https://github.com/petrolpark/Destroy/assets/151878567/75dce7aa-72ac-43d4-9f20-a764bf0e77f4)
i have uploaded a log.
https://gist.github.com/nicbou0321/1beb2b3479c1df2d68b37386b363b636

i had to get help from neoforge discord cuz tbh, its my first time trying to resolve a java bug and get mc working. 
im not much of a coder so java vomit i got no clue what it means. 
but all i know is that if i remove destroy it all works. 

i updated everything possible, am on destroy 0.3 too. even updated java. 
i am currently on neoforge 47.1.84 but i also tried some forge version, same issue. 
i wish you the best of luck in fixing this bug, as this mod seems AWESOME!! and i really want to play together with a friend. 

if you need anything else from me ill try my best to provide with the information needed. 
i just hope this bug can get fixed :(

**Comment by petrolpark** [comment] 2024-01-11 12:39
Duplicate of #64. This is being looked into.

**Closed as not planned by petrolpark** 2024-01-11 12:39 UTC
Labels: 🐛 Bug
