### ISSUE TITLE
Game crashes when right-clicking a pee cauldron with a test tube

### ISSUE THREAD

**Issue by NthPhantom10** [petrolpark/Destroy#391] opened 2024-07-09 05:47 UTC
**Describe the bug**

basically when you click a pee-cauldron with a test tube, it will crash the game.

**To Reproduce**
pee in a cauldron, right click on said cauldron

**Expected Behavior**

the entire game will crash

**Minecraft Username**
NthPhantom10

**Comment by FlamingKetchup** [comment] 2024-07-09 06:29
Duplicate of #346, use a bottle for urine

**Closed as completed** 2024-07-09 07:33 UTC
Labels: 🐛 Bug
