### ISSUE TITLE
Wrong username in Early Bird trophy

### ISSUE THREAD

**Issue by Ninjdai1** [petrolpark/Destroy#26] opened 2024-01-05 15:49 UTC
My username is Ninjdai_, but the trophy shows up as Ninjdai's.
(I got it in 0.0, and I just updated to 0.2 because game wouldn't launch, could this be linked ?)
![image](https://github.com/petrolpark/Destroy/assets/65647523/5abcc62a-8f8c-404f-8895-48535fc6cf05)

Forge 47.2.0
Create 0.5.1.f
Destroy 0.0 and 0.2

**Comment by Ninjdai1** [comment] 2024-01-05 15:54
I created a new world in 0.2, and the bug is still present
![image](https://github.com/petrolpark/Destroy/assets/65647523/36844648-45c3-4ee3-bb9a-192abbdffc0d)

**Comment by petrolpark** [comment] 2024-01-05 16:02
Duplicate of #17
This will be fixed in 0.3.

**Closed as not planned by petrolpark** 2024-01-05 16:02 UTC
Labels: 🐛 Bug
