### ISSUE TITLE
anytime i try to put piss in my test tube (right click a cauldron full of piss with a test tube) it crashes the game

### ISSUE THREAD

**Issue by PineNut98** [petrolpark/Destroy#346] opened 2024-04-07 08:40 UTC
anytime i try to put piss in my test tube (right click a cauldron full of piss with a test tube) it crashes the game

**Comment by petrolpark** [comment] 2024-04-07 11:22
Duplicate of #338, fixed in 1.0. The test tube can only store mixtures though - urine must be pumped or stored in bottles.

**Closed as completed by petrolpark** 2024-04-07 11:22 UTC
Labels: 🐛 Bug
