### ISSUE TITLE
Сan't enter the world

### ISSUE THREAD

**Issue by YraShlyapin** [petrolpark/Destroy#70] opened 2024-01-07 09:23 UTC
when I try to connect to the world, it first loads, but after that it takes me to a page with servers and writes: connection lost invalid player data

**Comment by yegordeez** [comment] 2024-01-07 11:07
I ve got the same problem

**Comment by petrolpark** [comment] 2024-01-07 11:31
Duplicate of #10. This is being investigated in 0.3.

**Closed as not planned** 2024-01-07 11:32 UTC
Labels: 🐛 Bug
