### ISSUE TITLE
[0.5] Server crashes when player places down Vat Controller block or Dynamite

### ISSUE THREAD

**Issue by cjay567** [petrolpark/Destroy#167] opened 2024-01-20 23:20 UTC
Minecraft Version: 1.20.1
Forge Version: 47.2.20
Create Version: 1.20.1-0.5.1.f
Destroy Version: 0.5

Also of note: The bug does *not* seem to occur on LAN worlds, only on servers.

Log:

> [18:05:14] [Server thread/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[18:05:14] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at com.petrolpark.destroy.block.entity.VatControllerBlockEntity.addBehaviours(VatControllerBlockEntity.java:129) ~[destroy-1.20.1-0.5.jar%23131!/:0.5] {re:classloading}
        at com.simibubi.create.foundation.blockEntity.SmartBlockEntity.<init>(SmartBlockEntity.java:49) ~[create-1.20.1-0.5.1.f.jar%23129!/:0.5.1.f] {re:classloading,re:mixin}
        at com.petrolpark.destroy.block.entity.VatControllerBlockEntity.<init>(VatControllerBlockEntity.java:113) ~[destroy-1.20.1-0.5.jar%23131!/:0.5] {re:classloading}
        at com.tterrag.registrate.builders.BlockEntityBuilder.lambda$createEntry$2(BlockEntityBuilder.java:139) ~[Registrate-MC1.20-1.3.3.jar%23171!/:?] {re:classloading}
        at net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:92) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at com.simibubi.create.foundation.block.IBE.m_142194_(IBE.java:58) ~[create-1.20.1-0.5.1.f.jar%23129!/:0.5.1.f] {re:classloading,re:mixin}
        at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:classloading,xf:fml:xaerominimap:xaero_chunkclass}
        at net.minecraft.world.level.Level.m_6933_(Level.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_7731_(Level.java:196) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:A}
        at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:163) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:classloading}
        at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:68) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:classloading}
        at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:classloading}
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:585) ~[forge-1.20.1-47.2.20-universal.jar%23156!/:?] {re:classloading}
        at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:245) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:tetra.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:358) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:computing_frames,re:classloading}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tetra.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinServerGamePacketListenerImpl,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23151!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
        ... 32 more
[18:05:14] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID dc37649f-ddcc-4c2a-8a6f-56435f3dac9d
[18:05:14] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\tjpc3\Desktop\server with jackie\.\crash-reports\crash-2024-01-20_18.05.14-server.txt
[18:05:14] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[18:05:14] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[18:05:14] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[18:05:15] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[18:05:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[18:05:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[18:05:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/ae2:spatial_storage
[18:05:16] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (world): All chunks are saved
[18:05:16] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:05:16] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:05:16] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[18:05:16] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
Press any key to continue . . .

**Comment by Faolon12** [comment] 2024-01-22 07:49
got this same issue with a modpack im working on, 4 by 4 platform of iron blocks, didnt finish placing glass yet, same forge and create version as above

**Comment by Faolon12** [comment] 2024-01-22 08:47
[crash-2024-01-22_07.50.39-server.txt](https://github.com/petrolpark/Destroy/files/14007387/crash-2024-01-22_07.50.39-server.txt)

**Comment by xandercreates** [comment] 2024-01-22 14:47
is there not a way to fix this?

**Comment by Faolon12** [comment] 2024-01-22 19:31
> is there not a way to fix this?

it will take time probably, the best way may be to figure out which mod its having issues with, my best bet rn,

**Comment by Faolon12** [comment] 2024-01-22 19:33
also the error thats there for invalid dist DEDICATED_SERVER is usually because of a client side mod,

**Comment by Faolon12** [comment] 2024-01-22 19:36
@cjay567 cjay, can you provide me a modlist of what you run on your server? id like to check a few things. maybe you to @XanderCreates if you have the same issue.

**Comment by cjay567** [comment] 2024-01-22 19:51
> @cjay567 cjay, can you provide me a modlist of what you run on your server? id like to check a few things. maybe you to @XanderCreates if you have the same issue.

Unfortunately, we tested it with all mods disabled except Create and Destroy, and the crash still occurred. I can give you the modlist anyways if you'd like, I don't think it would help much.

**Comment by Faolon12** [comment] 2024-01-22 21:26
ah ok

**Comment by Faolon12** [comment] 2024-01-22 21:56
`<html>
<body>

[22Jan2024 13:38:53.099] [Server thread/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
--
443 | [22Jan2024 13:38:53.100] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
444 | java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
445 | at com.petrolpark.destroy.block.entity.VatControllerBlockEntity.addBehaviours(VatControllerBlockEntity.java:129) ~[destroy-1.20.1-0.5.jar%23103!/:0.5]
446 | at com.simibubi.create.foundation.blockEntity.SmartBlockEntity.<init>(SmartBlockEntity.java:49) ~[create-1.20.1-0.5.1.f.jar%23102!/:0.5.1.f]
447 | at com.petrolpark.destroy.block.entity.VatControllerBlockEntity.<init>(VatControllerBlockEntity.java:113) ~[destroy-1.20.1-0.5.jar%23103!/:0.5]
448 | at com.tterrag.registrate.builders.BlockEntityBuilder.lambda$createEntry$2(BlockEntityBuilder.java:139) ~[Registrate-MC1.20-1.3.3.jar%23113!/:?]
449 | at net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:92) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
450 | at com.simibubi.create.foundation.block.IBE.m_142194_(IBE.java:58) ~[create-1.20.1-0.5.1.f.jar%23102!/:0.5.1.f]
451 | at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
452 | at net.minecraft.world.level.Level.m_6933_(Level.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
453 | at net.minecraft.world.level.Level.m_7731_(Level.java:196) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
454 | at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:163) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
455 | at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:68) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
456 | at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
457 | at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:585) ~[forge-1.20.1-47.2.20-universal.jar%23110!/:?]
458 | at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:245) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
459 | at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:355) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
460 | at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
461 | at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
462 | at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
463 | at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
464 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
465 | at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
466 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
467 | at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
468 | at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
469 | at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
470 | at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
471 | at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
472 | at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
473 | at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
474 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
475 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
476 | at java.lang.Thread.run(Thread.java:840) ~[?:?]
477 | Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
478 | at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:1.0]
479 | at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?]
480 | at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?]
481 | at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?]
482 | at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
483 | at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
484 | at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
485 | at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
486 | at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
487 | at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
488 | ... 32 more


</body>
</html>`

i just put the cleaner report from the modpack with only create and destroy.

**Comment by xandercreates** [comment] 2024-01-23 01:58
From what I can guess, The Mod is attempting to render certain features as if the mod was being run on an internal server/singleplayer world. Which is why LAN and/or Singleplayer worlds have no issue with this

(java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER) - taken from initial post

(java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
	at com.petrolpark.destroy.block.entity.DynamiteBlockEntity.addBehaviours(DynamiteBlockEntity.java:55) ~[destroy-1.20.1-0.5.jar%23278!/:0.5]) - Taken from my own server's crash report
	
To counter this on my server, I simply made it so no one can obtain those two blocks (until this is fixed)

**Comment by petrolpark** [comment] 2024-01-23 22:30
Fixed in 0.6.

**Closed as completed by petrolpark** 2024-01-23 22:30 UTC
Labels: 🐛 Bug

**Comment by xandercreates** [comment] 2024-01-24 14:04
I'm assuming 0.6 is being processed or is still being worked on
