### ISSUE TITLE
Game crashes when loading in

### ISSUE THREAD

**Issue by B0xKing** [petrolpark/Destroy#536] opened 2024-12-02 01:53 UTC
**Describe the bug**

Game crashes when loading into the game.

**To Reproduce**

Steps to reproduce the behavior.

1. Import the Following modpack into Curseforge ([Alchemical Industry-1.0.zip](https://github.com/user-attachments/files/17971463/Alchemical.Industry-1.0.zip))
2. Load the pack, game should crash.

**Expected Behavior**

The game should crash upon loading into the game.

**Screenshots**

![image](https://github.com/user-attachments/assets/c815a309-9068-452d-b875-783cd7c17476)

**System Information**

[Destroy (by Petrolpark)](https://www.curseforge.com/minecraft/mc-mods/destroy-chemistry)
[Create: Steam Powered (1.16/1.18/1.20) (by yuesha_yc)](https://www.curseforge.com/minecraft/mc-mods/steam-powered-create)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Create Thermal Compat (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/create-thermal-compat)
[Create Mechanical Extruder (by oierbravo_mc)](https://www.curseforge.com/minecraft/mc-mods/create-mechanical-extruder)
[Thermal Integration (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-integration)
[Create: Creative (by pyzpre)](https://www.curseforge.com/minecraft/mc-mods/create-creative)
[Mekanism Turrets & Fences (by SkelMaximus)](https://www.curseforge.com/minecraft/mc-mods/mekanism-turrets-fences)
[ExtendedAE (by GlodBlock)](https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider)
[Create: Ender Transmission (by Forsteri123)](https://www.curseforge.com/minecraft/mc-mods/create-ender-transmission)
[Thermal Endergy (by EpicSquid315)](https://www.curseforge.com/minecraft/mc-mods/thermal-endergy)
[Create: Liquid Fuel (by Forsteri123)](https://www.curseforge.com/minecraft/mc-mods/create-liquid-fuel)
[MEGA Cells (by ninety)](https://www.curseforge.com/minecraft/mc-mods/mega-cells)
[AE2 Things [Forge] (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/ae2-things-forge)
[Underground Villages, Stoneholm (by Reggarf)](https://www.curseforge.com/minecraft/mc-mods/underground-villages-stoneholm)
[Create Renewability (by TerraPixel)](https://www.curseforge.com/minecraft/mc-mods/create-renewability)
[Create: Applied Kinetics (by Forsteri123)](https://www.curseforge.com/minecraft/mc-mods/create-applied-kinetics)
[Create: Connected (by Lysine)](https://www.curseforge.com/minecraft/mc-mods/create-connected)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Multipart Machines: Grinding (by Grabolit)](https://www.curseforge.com/minecraft/mc-mods/multipart-machines-grinding)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Pipez (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/pipez)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[EMI (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/emi)
[Numina (by machinemuse)](https://www.curseforge.com/minecraft/mc-mods/numina)
[Thermal Cultivation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation)
[Create: Trading Floor (by CakeIsTastyDeveloper)](https://www.curseforge.com/minecraft/mc-mods/create-trading-floor)
[Petrolpark Library (by Petrolpark)](https://www.curseforge.com/minecraft/mc-mods/petrolpark-library)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Create: Diesel Generators (by george8188262)](https://www.curseforge.com/minecraft/mc-mods/create-diesel-generators)
[AE2 MEGA Things (by Lapipi)](https://www.curseforge.com/minecraft/mc-mods/ae2-mega-things)
[Create Encased (by iglee42)](https://www.curseforge.com/minecraft/mc-mods/create-encased)
[Glodium (by GlodBlock)](https://www.curseforge.com/minecraft/mc-mods/glodium)
[Ender IO (by crazypants_mc_the_second)](https://www.curseforge.com/minecraft/mc-mods/ender-io)
[Create: Quality Of Life (by iglee42)](https://www.curseforge.com/minecraft/mc-mods/create-qol)
[Create: Easy Structures (by M_Productions)](https://www.curseforge.com/minecraft/mc-mods/create-easy-structures)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Create: Netherless (Forge) (by DariusZeBaguette)](https://www.curseforge.com/minecraft/mc-mods/create-netherless)
[AE2: Better Villagers (by Reggarf)](https://www.curseforge.com/minecraft/mc-mods/ae2-better-villagers)
[Create: Ultimate Factory [Forge/Fabric] (by robinfrt)](https://www.curseforge.com/minecraft/mc-mods/create-ultimate-factory)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Chunk Loaders (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders)
[Create: Automate Everything (by MrAtomicBombHead)](https://www.curseforge.com/minecraft/mc-mods/create-automate-everything)
[Create: Addon Compatibility (by Amronos)](https://www.curseforge.com/minecraft/mc-mods/createaddoncompatibility)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Thermal Dynamics (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-dynamics)
[Create: Vintage Improvements (by Negodya1)](https://www.curseforge.com/minecraft/mc-mods/create-vintage-improvements)
[Create: Amazing Trading (by Robocraft999)](https://www.curseforge.com/minecraft/mc-mods/create-amazing-trading)
[Applied Energistics 2 (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Create: Molten Vents (by Apothicon)](https://www.curseforge.com/minecraft/mc-mods/create-molten-vents)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[ProjectE (by SinKillerJ)](https://www.curseforge.com/minecraft/mc-mods/projecte)
[Thermal Expansion (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Create Enchantment Industry Plus (by tiestoettoet08)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry-plus)
[Valkyrien Skies (Forge/Fabric) (by triode_)](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies)
[Inventory Sorter (by cpw)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)
[Create: Unify (by Luna)](https://www.curseforge.com/minecraft/mc-mods/create-unify)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Balm (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Sophisticated Storage (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage)
[Create: Enchantable Machinery (Forge) (by Cotrin)](https://www.curseforge.com/minecraft/mc-mods/create-enchantable-machinery)
[Project Expansion (by Donovan_DMC)](https://www.curseforge.com/minecraft/mc-mods/project-expansion)
[Thermal Innovation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-innovation)
[Lychee (Forge) (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/lychee)
[Create: Simple Ore Doubling [Forge/Fabric] (by robinfrt)](https://www.curseforge.com/minecraft/mc-mods/create-simple-ore-doubling)
[Extreme sound muffler - (Neo)Forge (by LeoBeliik)](https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler)
[Create: Better Villager (by Reggarf)](https://www.curseforge.com/minecraft/mc-mods/create-better-villager)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Applied Energistics 2 Wireless Terminals (by Mari_023)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals)
[Create Ore Excavation (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/create-ore-excavation)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Simple Clouds (by nonamecrackers2)](https://www.curseforge.com/minecraft/mc-mods/simple-clouds)
[Modular Powersuits (by machinemuse)](https://www.curseforge.com/minecraft/mc-mods/modular-powersuits)
[Create Compact Exp (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/create-compact-exp)
[Entangled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/entangled)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Create Thermal Ore Excavation (by Tomtaru)](https://www.curseforge.com/minecraft/mc-mods/create-thermal-ore-excavation)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Create Netherrack (by lukas_helms12321)](https://www.curseforge.com/minecraft/mc-mods/create-netherrack)
[Create: Copper & Zinc [Forge/Fabric] (by robinfrt)](https://www.curseforge.com/minecraft/mc-mods/create-copper-zinc)
[Create: Copycats+ (by Lysine)](https://www.curseforge.com/minecraft/mc-mods/copycats)
[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
[Ender Storage 1.8.+ (by covers1624)](https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Create: More Farmables [Forge/Fabric] (by Rockiecraft)](https://www.curseforge.com/minecraft/mc-mods/create-more-farmables)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[CodeChicken Lib 1.8.+ (by covers1624)](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8)
[Thermal Foundation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
[Create: More Automation (by Snakeypro)](https://www.curseforge.com/minecraft/mc-mods/create-more-automation)
[ME Requester (by Relentless)](https://www.curseforge.com/minecraft/mc-mods/merequester)
[Clockwork: Create x Valkyrien Skies (by rubydesic)](https://www.curseforge.com/minecraft/mc-mods/create-clockwork)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[Create: New Age (by nullBlade)](https://www.curseforge.com/minecraft/mc-mods/create-new-age)
[Create: Steam 'n' Rails (by IThundxr)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[Create: The Factory Must Grow (by Dr_Mango_Tea)](https://www.curseforge.com/minecraft/mc-mods/create-industry)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Create: Northstar (by lightning2401)](https://www.curseforge.com/minecraft/mc-mods/create-northstar)
[Create: Dreams & Desires (by Luna)](https://www.curseforge.com/minecraft/mc-mods/create-dreams-desires)
[Mekanism x Create: Northstar (by Wolfieboy09)](https://www.curseforge.com/minecraft/mc-mods/mekanism-x-create-northstar)
[Create Recycle Everything (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/create-recycle-everything)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Create Chromatic Return (by phicctv)](https://www.curseforge.com/minecraft/mc-mods/create-chromaticreturn)
[Easy Villagers (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/easy-villagers)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Create: The Recipe Expansion (by INFInight897)](https://www.curseforge.com/minecraft/mc-mods/create-recipe-expansion)
[AppliedE (by ninety)](https://www.curseforge.com/minecraft/mc-mods/appliede)
[Mekanism Extras (by lost_myself8)](https://www.curseforge.com/minecraft/mc-mods/mekanism-extras)
[Powah! (Rearchitected) (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected)
[Flux Networks (by sonar_sonic)](https://www.curseforge.com/minecraft/mc-mods/flux-networks)

All the most recent versions for Minecraft Forge 1.20.1 or most stable versions

**Additional context**

[crash-2024-12-02_12.45.48-client.txt](https://github.com/user-attachments/files/17971516/crash-2024-12-02_12.45.48-client.txt)

Crash can also be reproduce without any of the extra mods.

**Comment by MadeOfMo1ecules** [comment] 2024-12-02 02:05
What versions of Create and Destroy are you using?

**Comment by B0xKing** [comment] 2024-12-02 02:20
> What versions of Create and Destroy are you using?

Create 0.5.1j
Destroy 0.8

**Comment by MadeOfMo1ecules** [comment] 2024-12-02 04:47
Destroy 0.8 is probably not compatible with 0.5.1j. Additionally, it is not likely to be compatible with Petrol's Library, which was made for Destroy 0.1.0.

**Comment by MadeOfMo1ecules** [comment] 2024-12-11 17:11
Just took an extra look with this - there's an incompatibility with Sophisticated Backpacks, so this is likely a duplicate of #533

**Comment by petrolpark** [comment] 2024-12-21 15:29
A couple of duplicates

**Closed as completed by petrolpark** 2024-12-21 15:29 UTC
Labels: 🐛 Bug, ❌ Rejected
