### ISSUE TITLE
[Bug] Game Crash when building a vat. (Server side)

### ISSUE THREAD

**Issue by Hikari16665** [petrolpark/Destroy#201] opened 2024-01-24 02:23 UTC
Java version:17.0.3
Forge version:47.2.19

Game Log -> https://mclo.gs/D1XLQpi
Crash Report -> https://mclo.gs/xcituok

It can be recreated with only one mod; the crash report is the same.

**Comment by petrolpark** [comment] 2024-01-24 08:13
Duplicate of #167, fixed in 0.6.

**Closed as completed by petrolpark** 2024-01-24 08:13 UTC
Labels: 🐛 Bug
