### ISSUE TITLE
Aging Barrel can't work automatically

### ISSUE THREAD

**Issue by Catchmons** [petrolpark/Destroy#335] opened 2024-03-10 03:21 UTC
Aging barrel can only work automatically once. By the time when the first poccess was finished 99%, the alchol will be pump away, and the water, yeast, wheat will be left behind. Then the next poccess is blocked because the last poccess haven't been finished(stopped in 99%). And here is a screenshot. 
![2024-03-10_11 12 56](https://github.com/petrolpark/Destroy/assets/111665165/8268e6dd-497a-443a-9807-07b6bfbd0415)

**Comment by Catchmons** [comment] 2024-03-10 03:25
Maybe set the alchol could only be pumped after the proccess is finished can slove this problem. Or make aging barrel can't be inputed when proccess is going.

**Comment by mcclellanja** [comment] 2024-03-13 14:46
Not that it would be super elegant but can the aging barrel be interacted with by a deployer to open the lid and finish the process (it goes to 100% after you open the top) haven't tested it and can when I get home later.

**Comment by petrolpark** [comment] 2024-03-15 13:37
> Not that it would be super elegant but can the aging barrel be interacted with by a deployer to open the lid and finish the process (it goes to 100% after you open the top) haven't tested it and can when I get home later.

Agreed it's inelegant. The intended behaviour is for it to reach 100% and to be able to pump the product out without opening it.

**Comment by petrolpark** [comment] 2024-03-20 12:08
Fixed in 1.0.

**Closed as completed by petrolpark** 2024-03-20 12:08 UTC
Labels: 🐛 Bug

**Comment by Catchmons** [comment] 2024-03-20 14:50
> Fixed in 1.0.

Sorry to bother you, but is it normal for proton to oxidize iron into +III charge in-game？Regular proton shouldn't have such a strong oxidizability. Ferrous ion more reasonable, isn't it?
