### ISSUE TITLE
indentical liquids not properly adding with one another

### ISSUE THREAD

**Issue by ZathegamE** [petrolpark/Destroy#121] opened 2024-01-11 20:01 UTC
I have a setup that produces sulfuric acid, however when i try to combine all the pure sulfuric acid outputs they all remain in their individual tanks. The pipes produce particles as if they were transferring liquid, but they are not.
![2024-01-11_20 55 07](https://github.com/petrolpark/Destroy/assets/75631008/ae8319b6-dce5-4e73-9a0b-6aee1ad70081)
![2024-01-11_20 55 05](https://github.com/petrolpark/Destroy/assets/75631008/eef34d27-390b-429a-963f-36b1a9f8a8ca)
![2024-01-11_20 54 46](https://github.com/petrolpark/Destroy/assets/75631008/66390dd1-4975-4da5-ad30-4566c6661201)
![2024-01-11_20 54 45](https://github.com/petrolpark/Destroy/assets/75631008/bda5ef0b-b4dc-4512-a752-9f3275e37c82)

**Comment by petrolpark** [comment] 2024-01-11 21:18
Fixed in 0.4. The issue is that Create's tanks (and in fact fluid tanks in every mod) require fluid NBT to match exactly. As these are technically all slightly different it doesn't like it.

**Closed as completed by petrolpark** 2024-01-11 21:18 UTC
Labels: 🐛 Bug
