### ISSUE TITLE
[0.5 Bug] Placing Dynamite (with specific mod configuration) seemingly causes server crash [java.lang.BootstrapMethodError]

### ISSUE THREAD

**Issue by dylanjkl** [petrolpark/Destroy#185] opened 2024-01-21 22:55 UTC
1. Place dynamite item
2. The visual indicators for the dynamite resizing will appear for a second or two.
3. Disconnected client
4. Server Closed

[crash-2024-01-21_22.43.59-server.txt](https://github.com/petrolpark/Destroy/files/14003088/crash-2024-01-21_22.43.59-server.txt)

**Comment by petrolpark** [comment] 2024-01-21 22:57
I'm going to mark this as a duplicate of #167, as they have the same cause.

**Closed as completed by petrolpark** 2024-01-21 22:57 UTC
Labels: 🐛 Bug
