### ISSUE TITLE
Mixtures not going away in JEI bookmarks 

### ISSUE THREAD

**Issue by JJRobot25** [petrolpark/Destroy#84] opened 2024-01-08 13:03 UTC
When bookmarking a mixture in JEI (by pressing A), it adds "Water" (destroy:mixture), but when trying to remove it (by hitting A again), it doesn't go away, but instead adds it again. Reloading by using /reload seems to remove them.

![image](https://github.com/petrolpark/Destroy/assets/126060044/71a90bab-a203-4220-bcae-cf2b09ceade0)

**Comment by petrolpark** [comment] 2024-01-08 17:18
Duplicate of #59. Fixed in 0.3.

**Closed as completed by petrolpark** 2024-01-08 17:18 UTC
Labels: 🐛 Bug
