### ISSUE TITLE
[Bug] Multiplayer server startup crash, hosted on Exaroton, small custom modpack

### ISSUE THREAD

**Issue by ThePixelist** [petrolpark/Destroy#125] opened 2024-01-12 06:42 UTC
- **SYNOPSIS:** My small custom Destroy modpack crashes on startup on Exaroton.

- [**Server Crash Report on MCLo.gs**](https://mclo.gs/qw4czrh)
![image](https://github.com/petrolpark/Destroy/assets/51265804/682f23c0-96ba-4627-9b9d-866ef25f85d1)

# Information
- **HOSTING PROVIDER:** **Exaroton** [with Simple Voice Chat installed. For Exaroton, the port should be set to `-1`, which ostensibly uses the Minecraft server port. However, the server didn't have a world yet, meaning there was no configuration]. Runs **Java 17 GraalVM**.

- **CLIENT MODLIST:**
	- Cloth Config v10 API (11.1.118)
	- Create (0.5.1.f)
	- Destroy (0.3)
	- Embeddium (0.2.16+mc1.20.1)
	- EntityCulling (1.6.2)
	- FallingTree (4.3.4)
	- Ferrite Core (6.0.01)
	- JEI (15.2.0.27)
	- Moonlight Library (1.20-2.8.82)
	- Mouse Tweaks (2.25)
	- Multiplayer Server Pause (1.1.0)
	- Notes (1.20.1-1.3.0-forge)
	- OpenLoader (19.0.3)
		- The DynamicLights datapack is installed, meaning any singleplayer worlds will include it.
	- Simple Voice Chat (1.20.1-2.4.32)
	- Supplementaries (1.20-2.7.21)
	Forge 1.20.1 - 47.2.19
	The client modpack is a custom modpack ran on PrismMC, with JDK 17.0.2
	The modpack was updated to the latest mods today, 2024 Jan 12 Fri.

- **SERVER MODLIST:**
	- Cloth Config v10 API (11.1.118)
	- Create (0.5.1.f)
	- Destroy (0.3)
	- FallingTree (4.3.4)
	- Ferrite Core (6.0.1)
	- JEI (15.2.0.27)
	- Moonlight (1.20-2.8.82)
	- Multplayer Server Pause (1.1.0)
	- Simple Voice Chat (1.20.1-2.4.32)
	- Supplementaries (1.20-2.7.21)
	Forge 1.20.1 - 47.2.19
	Note that, as the world cannot generate, the DynamicLights datapack is not installed.
	3GB of RAM and 1.5 Shared CPU Cores are allocated.
	The modpack was updated to the latest mods today, 2024 Jan 12 Fri.

**Comment by ShubaOS** [comment] 2024-01-12 09:47
I'm self hosting and also having a similar problem getting the server to start with Destroy installed.

**Comment by petrolpark** [comment] 2024-01-12 10:31
Duplicate of #102, fixed in 0.4.

**Closed as completed by petrolpark** 2024-01-12 10:31 UTC
Labels: 🐛 Bug

**Comment by ShubaOS** [comment] 2024-01-12 19:05
> Duplicate of #102, fixed in 0.4.

Do you have an estimate on when v0.4 will be released?
