### ISSUE TITLE
Russian players can not use this mod

### ISSUE THREAD

**Issue by eecler** [petrolpark/Destroy#83] opened 2024-01-08 11:44 UTC
If you play from a Russian IP address, you will not be allowed into the game. My assumption is that the mod connects to Patreon (patreon is blocked in the Russian Federation) or to other resources banned on the territory of the Russian Federation.

Play can only if you run VPN.

**Comment by BytinYarota** [comment] 2024-01-08 12:58
I'm able to successfully run the game while unable to connect to Patreon directly. I guess it doesn't involves Patreon while other banned resources might be possible.
Quiet wierd issue though XD

**Comment by petrolpark** [comment] 2024-01-08 17:19
Duplicate of #10.

**Closed as not planned** 2024-01-08 17:19 UTC
Labels: 🐛 Bug
