### ISSUE TITLE
It will cause online failure

### ISSUE THREAD

**Issue by Xuezhi-Yang** [petrolpark/Destroy#88] opened 2024-01-09 01:11 UTC
I can enter the game normally, but when my friend connects to my server, an error message "ecoderException: java.lang.NullPointerException: Cannot invoke Internal Exception: io.netty.handler.codec.[ geRegistry.getvalue(int) because "registry" is null net.minecraftforge.registries.Fo" appears.
After we removed this module, we could go online normally.

**Comment by Xuezhi-Yang** [comment] 2024-01-09 01:15
My friend is sleeping,so I can't give you the log.

**Comment by petrolpark** [comment] 2024-01-09 01:18
Duplicate of #64.

**Closed as not planned by petrolpark** 2024-01-09 01:18 UTC
Labels: 🐛 Bug
