### ISSUE TITLE
Crash when looking at uses for Distilled Water with thermal expansion installed

### ISSUE THREAD

**Issue by medsal15** [petrolpark/Destroy#33] opened 2024-01-05 19:11 UTC
Crash report: https://pastebin.com/raw/yF3ctVF5

Mod versions:
- Forge 47.2.1
- JEI 15.2.0.27
- Create 0.5.1f
- Destroy 0.2
- CoFH Core 11.0.0.51
- Thermal Foundation 11.0.2.64
- Thermal Expansion 11.0.0.27

**Comment by petrolpark** [comment] 2024-01-07 15:28
Are you sure that's the right crash report? This says it crashed when initializing the game.

**Comment by petrolpark** [comment] 2024-01-07 15:29
There was a bug involving looking at recipes of mixtures which has now been fixed in 0.3, but that's not what caused this.

**Comment by medsal15** [comment] 2024-01-07 16:57
You're right, that's the one I got when I forgot to enable cofh core when checking which mod was causing it. This is the correct crash report https://pastebin.com/raw/rfN7jQ0f

**Comment by petrolpark** [comment] 2024-01-07 18:39
Yep, this has been fixed in 0.3. (Duplicate of #28) Thanks for your help!

**Closed as completed by petrolpark** 2024-01-07 18:39 UTC
Labels: 🐛 Bug
