### ISSUE TITLE
Ticking entity error when attempting to add LPG to a vat

### ISSUE THREAD

**Issue by EvilBreaker** [petrolpark/Destroy#67] opened 2024-01-06 23:57 UTC
Could probably be simplified as "Ticking entity error when adding something to a vat"
[crash-2024-01-06_18.55.15-server.txt](https://github.com/petrolpark/Destroy/files/13851697/crash-2024-01-06_18.55.15-server.txt)

**Comment by petrolpark** [comment] 2024-01-07 11:30
Duplicate of #54

**Closed as not planned** 2024-01-07 15:29 UTC
Labels: 🐛 Bug
