### ISSUE TITLE
Game Crashes when standing on the create train station block

### ISSUE THREAD

**Issue by idklolwhatisGithub** [petrolpark/Destroy#77] opened 2024-01-07 23:37 UTC
whenever you stand on the train station block my game crashes. I tested this with only with JEI, Create and Destroy

**Comment by Plite7067** [comment] 2024-01-08 07:10
please can you attach your latest.log file here

**Comment by petrolpark** [comment] 2024-01-08 17:22
This caused by the same thing as #14, which should be fixed in 0.3.

**Closed as completed by petrolpark** 2024-01-08 17:22 UTC
Labels: 🐛 Bug
