### ISSUE TITLE
baby villager doesnt pick up bucket and spades

### ISSUE THREAD

**Issue by luluthepogcat** [petrolpark/Destroy#278] opened 2024-02-14 07:52 UTC
when i throw the bucket and spades to the baby villager it doesnt pick the toy up
![2024-02-14_14 51 14](https://github.com/petrolpark/Destroy/assets/154001303/90026394-33c3-4445-bbbd-62eb4eccabcc)

**Comment by petrolpark** [comment] 2024-02-15 11:42
@luluthepogcat  Do they not pick it up if you throw it directly at them, or is it just that they don't pathfind to it when you are nearby? If it's the latter case, this behaviour is shared by Villagers (and indeed any mob), who have higher priority things to do (in the case of Baby Villagers, they tend to focus on the Player and other Villagers) and so that probably won't be addressed by Destroy. If you are sufficiently far away they eventually decide to go and pick it up.

**Comment by petrolpark** [comment] 2024-02-17 12:47
Closing due to lack of a response. I believe the intended behaviour is happening.

**Closed as not planned by petrolpark** 2024-02-17 12:47 UTC
Labels: 🐛 Bug

**Comment by luluthepogcat** [comment] 2024-02-17 12:50
> Closing due to lack of a response. I believe the intended behaviour is happening.

Oh shoot i tested again but forgot to reply, but yes the villager is indeed not give a damn for the cool toy on the ground, even if i walk away and do some building, btw can you make baby village cry when they see other villager gets killed or when a raid happens?
