### ISSUE TITLE
Vat Temperature Bug 1.20.1

### ISSUE THREAD

**Issue by jombothegoodcat** [petrolpark/Destroy#371] opened 2024-06-09 03:44 UTC
I was using the destroy mod and I was trying to completely empty a vat for some other stuff, first emptying through a mechanical pump went well before temperature dropped to below -200 C, so I put 4 blaze burners and the temperature proceeded to exponentially increase very rapidly and wouldn't stop, I did take this clip in the middle of that extravaganza: [https://medal.tv/games/minecraft/clips/i1ZCmqx8QAeb4keW4/d13371HJKKjm?invite=cr-MSxBRm4sMTg4ODg3ODM4LA]

The pressure was stuck at around -100.5k kPa but the vat did eventually blow up (unsure as to how), but not before reaching a bit above a whopping 30 x 10^36 C in its final moments, to replicate what I did:
1. Make a 2x2x2 vat out of copper casing
2. Keep it powered with 4 blaze burners underneath
3. Use a mechanical pump to continuously pump out the nitrogen and oxygen (I highly recommend a creative motor on max rpm to pump it out fast)
4. Make sure to right click one of the walls of the vat with a wrench to get the temperature gauge, having a pressure gauge is optional
I do recommend a VERY tall 3x3 tank because the amount of the nitrogen/oxygen mixtures extracted seems to be infinitely growing even though only 0 moles are left, and yes I am using the latest versions of the create mod and the destroy mod along with JEI.

fyi "coolguyOP" is my mc user and "jombothegoodcat" is my discord

**Comment by gri16m** [comment] 2024-06-16 21:05
It's understandable why the temperature went so low because of the ideal gas law, but the 30 x 10^36 C temperature when heating is a bit ludicrous? I'm not a professional by any means, but sure the temperature will go up quickly when there's so little to heat but I don't think it should be that high.

Also I found a way to accomplish what you're looking for but I do have the vat explosion setting in destroy disabled. (the pressure did say -101kPa so anything other than glass should work?)
![2024-06-16_16 20 42](https://github.com/petrolpark/Destroy/assets/172697622/3db2f615-c57a-430d-9360-81fabce19f23)
Just make a vat and cool it enough so that all the gas in the vat condenses and fill ~25 test tubes to remove everything but you'll have to add something with a test tube to get the vat working again

**Comment by ToastbrotExe** [comment] 2024-06-30 13:07
Looks like issue #240 is still present

**Comment by jombothegoodcat** [comment] 2024-07-06 14:51
Also here is a clip of the moment that it blew up, audio removed due to it being too loud: https://medal.tv/games/minecraft/clips/i1ZJHJ85txiDdkW3c/d1337CeFyUkI?invite=cr-MSxoZVksMTg4ODg3ODM4LA

**Comment by petrolpark** [comment] 2024-10-02 07:58
I'm going to mark as a duplicate of #240

**Closed as not planned by petrolpark** 2024-10-02 07:58 UTC
Labels: 🐛 Bug
